version: '3'

services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/db
      - ./logs:/var/log/db

  wp:
    build:
      context: ./docker/wp
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html

  wpcli:
    image: wordpress:cli
    command: /bin/sh -c 'sleep 10;'
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
      - wp

volumes:
  db_data:
