version: '3.3'

services:
  database:
    build:
      context: ./docker/databese
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
      - ./logs:/var/log/mysql

  wordpress:
    build:
      context: ./docker/wordpress
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html

volumes:
  db_data:
